# Generated by Django 3.2.16 on 2023-01-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='имя')),
                ('city', models.CharField(max_length=20, verbose_name='город')),
                ('place_type', models.SlugField(verbose_name='Вид заведения')),
                ('review', models.TextField(verbose_name='отзыв')),
                ('url', models.URLField(verbose_name='ссылка на сайт заведения')),
            ],
        ),
    ]
