# Generated by Django 3.2.16 on 2023-01-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0002_auto_20230116_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='sponsored',
            field=models.BooleanField(default=True, verbose_name='проплачено'),
        ),
    ]
