# Generated by Django 3.2.16 on 2023-01-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0003_alter_place_sponsored'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('cf', 'Кафе'), ('br', 'Бар'), ('rs', 'Ресторан'), ('ff', 'Фастфуд'), ('pz', 'Пиццерия')], max_length=15, verbose_name='Вид заведения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='sponsored',
            field=models.BooleanField(default=False, verbose_name='проплачено'),
        ),
    ]
