# Generated by Django 3.2.16 on 2023-01-26 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bot_admin', '0004_auto_20230116_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='created',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 1, 26, 11, 37, 51, 634865, tzinfo=utc), verbose_name='Дата добавления'),
        ),
    ]
