# Generated by Django 4.1.7 on 2023-02-22 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="отзывы")),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Дата добавления",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="имя")),
                (
                    "city",
                    models.CharField(max_length=20, verbose_name="город"),
                ),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("cf", "Кафе"),
                            ("br", "Бар"),
                            ("rs", "Ресторан"),
                            ("ff", "Фастфуд"),
                            ("pz", "Пиццерия"),
                        ],
                        max_length=15,
                        verbose_name="Вид заведения",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="описание"),
                ),
                (
                    "url",
                    models.URLField(verbose_name="ссылка на сайт заведения"),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Дата добавления",
                    ),
                ),
                (
                    "sponsored",
                    models.BooleanField(
                        default=False,
                        verbose_name="проплачено",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="широта",
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True,
                        null=True,
                        verbose_name="долгота",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        help_text="отзывы пользователей",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administration.review",
                        verbose_name="отзывы",
                    ),
                ),
            ],
            options={
                "verbose_name": "заведение",
                "verbose_name_plural": "заведения",
            },
        ),
    ]
