# Generated by Django 4.1.7 on 2023-02-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="url",
            field=models.URLField(
                null=True, verbose_name="ссылка на сайт заведения"
            ),
        ),
    ]
