# Generated by Django 4.1.7 on 2023-03-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_alter_place_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="adress_name",
            field=models.TextField(blank=True, verbose_name="описание"),
        ),
    ]
