# Generated by Django 4.1.7 on 2023-05-27 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0002_alter_placetype_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="place",
            name="place_type",
        ),
        migrations.RenameModel(
            old_name="PlaceType",
            new_name="Category",
        ),
        migrations.DeleteModel(
            name="PlaceTypePlace",
        ),
        migrations.AddField(
            model_name="categoryplace",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="administration.category",
            ),
        ),
        migrations.AddField(
            model_name="categoryplace",
            name="place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="administration.place",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="category",
            field=models.ManyToManyField(
                max_length=30,
                through="administration.CategoryPlace",
                to="administration.category",
                verbose_name="вид заведения",
            ),
        ),
    ]
