# Generated by Django 4.1.7 on 2023-05-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0003_categoryplace_remove_place_place_type_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="address_name",
            new_name="address",
        ),
    ]
