# Generated by Django 4.1.7 on 2023-06-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0003_city_left_box_latitude_city_left_box_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="широта"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="долгота"
            ),
        ),
    ]
