# Generated by Django 4.1.7 on 2023-03-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0003_place_adress_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="place",
            old_name="adress_name",
            new_name="address_name",
        ),
        migrations.AddField(
            model_name="place",
            name="worktime_from",
            field=models.TimeField(
                blank=True,
                db_index=True,
                default=None,
                verbose_name="Время работы, с",
            ),
        ),
        migrations.AddField(
            model_name="place",
            name="worktime_to",
            field=models.TimeField(
                blank=True,
                db_index=True,
                default=None,
                verbose_name="Время работы, до",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="place_type",
            field=models.CharField(
                choices=[
                    ("cf", "Кафе"),
                    ("br", "Бар"),
                    ("rs", "Ресторан"),
                    ("ff", "Фастфуд"),
                    ("pz", "Пиццерия"),
                ],
                max_length=15,
                verbose_name="вид заведения",
            ),
        ),
    ]
