# Generated by Django 4.1.7 on 2023-03-09 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0004_rename_adress_name_place_address_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="PlaceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=30, verbose_name="тип заведения"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="place",
            name="worktime_from",
            field=models.TimeField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Время работы, с",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="worktime_to",
            field=models.TimeField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Время работы, до",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="place_type",
            field=models.ForeignKey(
                max_length=15,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="administration.placetype",
                verbose_name="вид заведения",
            ),
        ),
    ]
