# Generated by Django 4.1.7 on 2023-05-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_rename_address_name_place_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "latitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="широта"
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        blank=True, null=True, verbose_name="долгота"
                    ),
                ),
            ],
            options={
                "verbose_name": "город",
                "verbose_name_plural": "города",
            },
        ),
        migrations.RemoveConstraint(
            model_name="place",
            name="administration_place_unique_relationships",
        ),
        migrations.AddField(
            model_name="place",
            name="phone",
            field=models.TextField(
                blank=True, null=True, verbose_name="телефонный номер"
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("name", "address", "city"),
                name="administration_place_unique_relationships",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="places",
                to="administration.city",
                verbose_name="город",
            ),
        ),
    ]
