# Generated by Django 4.1.7 on 2023-06-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_alter_place_latitude_alter_place_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="latitude",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="широта"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="longitude",
            field=models.CharField(
                blank=True, max_length=11, null=True, verbose_name="долгота"
            ),
        ),
    ]
