# Generated by Django 4.1.7 on 2023-06-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0005_alter_place_latitude_alter_place_longitude"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "город", "verbose_name_plural": "городов"},
        ),
    ]
