# Generated by Django 4.1.7 on 2023-03-09 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0005_placetype_alter_place_worktime_from_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="address_name",
            field=models.TextField(
                blank=True, null=True, verbose_name="описание"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="описание"
            ),
        ),
    ]
