# Generated by Django 4.1.7 on 2023-03-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0006_alter_place_address_name_alter_place_description",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="place_type",
        ),
        migrations.CreateModel(
            name="PlaceTypePlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="administration.place",
                    ),
                ),
                (
                    "place_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="administration.placetype",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="place",
            name="place_type",
            field=models.ManyToManyField(
                max_length=15,
                through="administration.PlaceTypePlace",
                to="administration.placetype",
                verbose_name="вид заведения",
            ),
        ),
    ]
