# Generated by Django 4.1.7 on 2023-07-05 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0006_alter_city_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(max_length=100, verbose_name="имя"),
        ),
    ]
