# Generated by Django 4.1.7 on 2023-03-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0007_remove_place_place_type_placetypeplace_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("name", "city"),
                name="administration_place_unique_relationships",
            ),
        ),
    ]
