# Generated by Django 4.1.7 on 2023-08-02 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0007_alter_place_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={
                "verbose_name": "город",
                "verbose_name_plural": "города",
            },
        ),
    ]
