# Generated by Django 4.1.7 on 2023-03-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0008_place_administration_place_unique_relationships",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placetype",
            options={"verbose_name": ("тип заведения",)},
        ),
        migrations.AlterField(
            model_name="placetype",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
