# Generated by Django 4.1.7 on 2023-03-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0009_alter_placetype_options_alter_placetype_name",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="placetype",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
