# Generated by Django 4.1.7 on 2023-03-13 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0010_alter_placetype_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="place",
            name="administration_place_unique_relationships",
        ),
        migrations.AlterField(
            model_name="place",
            name="review",
            field=models.ForeignKey(
                blank=True,
                help_text="отзывы пользователей",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to="administration.review",
                verbose_name="отзывы",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("name", "address_name", "city"),
                name="administration_place_unique_relationships",
            ),
        ),
    ]
