# Generated by Django 4.1.7 on 2023-03-13 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "administration",
            "0011_remove_place_administration_place_unique_relationships_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={
                "default_related_name": "places",
                "verbose_name": "заведение",
                "verbose_name_plural": "заведения",
            },
        ),
        migrations.AlterField(
            model_name="place",
            name="review",
            field=models.ForeignKey(
                blank=True,
                help_text="отзывы пользователей",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="administration.review",
                verbose_name="отзывы",
            ),
        ),
    ]
