# Generated by Django 4.1.7 on 2023-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0012_alter_place_options_alter_place_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="name",
            field=models.CharField(max_length=60, verbose_name="имя"),
        ),
    ]
