# Generated by Django 4.1.7 on 2023-03-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0013_alter_place_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="place",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="administration.place",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="place",
            name="review",
            field=models.TextField(
                blank=True, null=True, verbose_name="отзыв"
            ),
        ),
    ]
