# Generated by Django 4.1.7 on 2023-03-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0014_review_place_alter_place_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="review",
        ),
        migrations.AlterField(
            model_name="place",
            name="city",
            field=models.CharField(max_length=30, verbose_name="город"),
        ),
        migrations.AlterField(
            model_name="place",
            name="place_type",
            field=models.ManyToManyField(
                max_length=30,
                through="administration.PlaceTypePlace",
                to="administration.placetype",
                verbose_name="вид заведения",
            ),
        ),
    ]
