# Generated by Django 4.1.7 on 2023-03-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0016_review_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="url",
            field=models.URLField(
                blank=True,
                null=True,
                verbose_name="ссылка на сайт заведения",
            ),
        ),
    ]
