# Generated by Django 4.1.7 on 2023-03-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0017_alter_place_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="placetypeplace",
            options={
                "verbose_name": "тип заведения",
                "verbose_name_plural": "типы заведений",
            },
        ),
    ]
